Gemfile, Gemfile.lock
- [] Reviewed
- [] Bug Fix
* description
Add boostrap gem
=> bootstrap setup

Gemfile
- [] Reviewed
- [] Bug Fix
* description
Add Figaro, Faraday and Capybara to gemfile.
=> add capybara figaro and faraday to gem

Gemfile, app/controllers/welcome_controller.rb, app/views/layouts/application.html.erb, app/views/welcome/index.html.erb, config/routes.rb, db/schema.rb, spec/features/any_type_of_user_visits_root_spec.rb
- [] Bug Fix
* description
-Create Root Welcome Page
-Page has welcome message, slogan and link to /login
=> #1 create root with welcome message slogan and login link

.gitignore, app/assets/stylesheets/application.css, app/controllers/welcome_controller.rb, app/views/layouts/application.html.erb, app/views/welcome/index.html.erb, config/routes.rb, spec/features/nav_bar_links_spec.rb
- [] Bug Fix
* description
-Adds nav bar, with links for visitors.
-Tests link paths
-Tests that logged in user links do not show up.
* closes #2 
=> #2 add nav bar with links for visitors

Gemfile.lock, app/views/welcome/show.html.erb, spec/features/a_user_can_visit_about_page_spec.rb
- [] Bug Fix
* description
* closes #3 
Adds an about page
=> 3 about page mt

app/models/trip.rb, db/migrate/20181219005146_create_trips.rb, db/schema.rb, spec/factories/trips.rb, spec/models/trip_spec.rb
* description
* closes #17 
- [] This broke nothing
=> Add trip table

app/assets/stylesheets/application.css, app/views/layouts/application.html.erb, app/views/welcome/index.html.erb
- [] Bug Fix
* description
Sweet styling for the root page
* closes
=> 22 root styling

app/assets/stylesheets/application.css, app/views/layouts/application.html.erb, app/views/welcome/index.html.erb, app/views/welcome/show.html.erb
- [] Bug Fix
* description
- Updates styling on root and nav to fit mobile.  
* closes #22 
=> update styling on root and nav links

app/assets/stylesheets/application.scss
* description
Changes css file to scss to fix asset precompile issue.  
Should be ready to deploy. 
* closes
#27 
=> fix asset for background images

app/assets/javascripts/geolocation.js, app/views/layouts/application.html.erb, app/views/trips/new.html.erb
- [] Implemented
- [] Reviewed
- [] Bug Fix
* description
Geolocation through browser using javascript
* closes
=> geolocation services

app/models/trip.rb, db/migrate/20181219005146_create_trips.rb, db/schema.rb, spec/models/trip_spec.rb
- [] Bug Fix
* description
Updates migration, model and test to better fit our needs
* closes
=> update trip migration, model and test

app/assets/javascripts/results.coffee, app/assets/stylesheets/results.scss, app/controllers/results_controller.rb, app/controllers/trips_controller.rb, app/helpers/results_helper.rb, app/views/results/create.html.erb, app/views/trips/new.html.erb, config/routes.rb
- [] Bug Fix
* description
adds results controller and moves some functionality
* closes
=> lays out the skeleton for controllers

app/controllers/results_controller.rb, app/facades/results_facade.rb, app/models/lot.rb, app/views/results/index.html.erb, spec/features/user_can_add_new_trip_spec.rb
- [] Bug Fix
* description
Add infrastructure to make Parkwhiz API call and deliver lot objects to the results index view. Testing will probably need to be changed as view is updated
* closes
=> 20 parkwhiz api call

app/controllers/results_controller.rb, app/facades/results_facade.rb, app/views/results/index.html.erb
- [] Bug Fix
* description
Adds functionality to put parking lot results on the map. 
* closes
=> Parkween results

app/assets/stylesheets/application.scss, app/views/results/index.html.erb
- [] Bug Fix
* description
-Adds styling to results page. 
-Limits meter results to the closest 10 meters
* closes n/a
=> add style to results page

Gemfile, Gemfile.lock, config/newrelic.yml
- [] Bug Fix
* description
Adds New Relic
* closes
=> Adds new relic.

app/controllers/sessions_controller.rb, spec/features/user_logs_in_via_google_ominauth_spec.rb
- [] Bug Fix
* description
Changes redirect path to new trip after login
Writes an effective test for google oauth login
Gets testing coverage to 100%
* closes
=> write test for oauth, coverage at 100

app/views/results/index.html.erb
- [] Implemented
- [] Bug Fix
* description
Moves map to top of screen on results page.  More work to be done here but push this so other group members can work on their portions.  
* closes
=> rearrange map on results page

app/assets/stylesheets/application.scss, app/models/user.rb, app/views/trips/index.html.erb, spec/factories/trips.rb, spec/features/form_creates_api_call_spec.rb, spec/features/user_can_see_trip_history_spec.rb
- [] Bug Fix
* description
Adds data to trips history index page.
Will need to connect the create function on the results page in order to get this to work 100%
* closes #58 
=> update to trip index page

app/assets/javascripts/form.js, app/assets/stylesheets/application.scss, app/views/trips/new.html.erb
-[x] New feature
- [] Bug Fix
* description
Adds a multipage form using jquery!!! 
* closes
=> Multi form

Gemfile, config/environments/production.rb
* description
Updates production environment and gemfile to make Heroku happy :)
* closes
=> fix heroku rake and compile assets

app/assets/stylesheets/application.scss
- [] Bug Fix
* description
Changes position and color of "Next"  buttons on multi page form.
* closes
=> Change position and color of next buttons on form.

app/assets/stylesheets/application.scss, app/facades/results_facade.rb, app/services/meter_service.rb, app/views/results/index.html.erb, app/views/trips/new.html.erb, spec/features/user_can_add_new_trip_spec.rb, spec/features/user_can_see_stats_spec.rb
* description
Styling to stats area on results page
Meter Stats added
Bug fix on meter service.  (Meter was returning meters outside of radius, instead of inside)
Removed extra button from search page (current location button, not needed at this time)
Increased font size in map info window
* closes #65 
=> 65 meter stats

app/facades/results_facade.rb, app/views/results/index.html.erb, spec/features/user_can_see_stats_spec.rb
- [] Bug Fix
* description
Added stats for lots
* closes #67 
=> 67 lot stats

Gemfile, app/assets/stylesheets/application.scss, app/controllers/results_controller.rb, app/controllers/trips_controller.rb, app/facades/results_facade.rb, app/views/results/index.html.erb, app/views/trips/new.html.erb, spec/features/user_can_add_new_trip_spec.rb, spec/features/user_can_see_stats_spec.rb
* description
User can now select a marker on the results page map for a lot and see a button to save the specific destination in their trips
* closes #69 
=> 69 result selection

Gemfile, Gemfile.lock, app/assets/javascripts/results.coffee, spec/features/user_can_see_stats_spec.rb
- [] Implemented
- [] Reviewed
- [] Bug Fix
* description
* closes
- [] This broke nothing
=> updates gemfile

app/assets/stylesheets/application.scss, app/views/results/index.html.erb, app/views/trips/new.html.erb, spec/features/user_can_add_new_trip_spec.rb
* description
Adds choose meter button to results page only if they selected meters on the previous page, tested
Removed extra content from results page
* closes
=> Meter select

app/views/results/index.html.erb
* description
Modified ui of the map
* closes n/a
=> Map tweaking

app/views/layouts/application.html.erb
- [] Reviewed
- [] Bug Fix
* description
gets rid of unused geolocation button
* closes
- [] This broke nothing
=> Gets rid of button for geolocation.

app/controllers/trips_controller.rb, app/views/trips/index.html.erb, app/views/trips/new.html.erb, spec/features/any_type_of_user_visits_root_spec.rb
- [] Reviewed
* description
Adds login button to /trips and /trips/new so that a guest user has to login to user the app
* closes
=> Add conditional logic to views to add login button

app/views/trips/index.html.erb, app/views/trips/new.html.erb
- [] Bug Fix
* description
adds an external link to google maps for directions to chosen spot and reorganizes trips index
* closes
- [] This broke nothing
=> Directions
